var res = {
    HelloWorld_png: "res/HelloWorld.png",
    desk_jpg: "res/graphics/desk.jpg",
    login_jpg: "res/login.jpg",
    menu_jpeg:"res/menu_bg.jpg",

    desk_jpg: "res/graphics/desk.jpg",
    redmiddle_png: "res/graphics/redmiddle.png",
    endPad_jpg: "res/graphics/endPad.jpg",
    bg_setup_png: "res/graphics/bg_setup.png",
    bg_final_png: "res/graphics/bg_final.png",
    bg_1_jpg: "res/graphics/bg_1.jpg",
    b_1_jpg: "res/graphics/b_1.jpg",
    b_2_jpg: "res/graphics/b_2.jpg",
    back_jpg: "res/graphics/back.jpg",
    back_1_jpg: "res/graphics/back_1.jpg",
    chat_1_png: "res/graphics/chat_1.png",
    chat_2_png: "res/graphics/chat_2.png",
    num_1_png: "res/graphics/num_1.png",
    num_2_png: "res/graphics/num_2.png",
    num_3_png: "res/graphics/num_3.png",
    num_4_png: "res/graphics/num_4.png",
    num_5_png: "res/graphics/num_5.png",
    num_6_png: "res/graphics/num_6.png",
    num_7_png: "res/graphics/num_7.png",
    num_8_png: "res/graphics/num_8.png",
    num_9_png: "res/graphics/num_9.png",
    bg_input_png: "res/graphics/bg_input.png",
    checkbox_bg_png: "res/graphics/checkbox_bg.png",
    checkbox_select_png: "res/graphics/checkbox_select.png",
    createRoom_bg_png: "res/graphics/createRoom_bg.png",
    joinRoom_bg_png: "res/graphics/joinRoom_bg.png",
    bg_input_up_png: "res/graphics/bg_input_up.png",
    close:"res/graphics/close.png",
    gun_png:"res/graphics/gun.png",
    bullet_png:"res/graphics/bullet.png",
    bg_input_down_png: "res/graphics/bg_input_down.png",
    fate_019_png: "res/graphics/fate_019.png",
    icon_prepare_png:"res/graphics/icon_prepare.png",
    icon_create_png:"res/graphics/icon_create.png",
    icon_back_png:"res/graphics/icon_back.png",
    icon_effect_png:"res/graphics/icon_effect.png",
    icon_music_png:"res/graphics/icon_music.png",
    icon_head_png:"res/graphics/icon_head.png",
    icon_clock_png:"res/graphics/icon_clock.png",
    icon_r_png:"res/graphics/icon_r.png",
    icon_ting_png:"res/graphics/icon_ting.png",
    icon_help_png:"res/graphics/icon_help.png",
    icon_inverted_png:"res/graphics/icon_inverted.png",
    btn_admit_png:"res/graphics/btn_admit.png",
    btn_refuse_png:"res/graphics/btn_refuse.png",

    icon_head1_png:"res/graphics/icon_head1.png",
    icon_ok_png:"res/graphics/icon_ok.png",
    icon_confirm_png:"res/graphics/icon_confirm.png",
    icon_recorder_png:"res/graphics/icon_recorder.png",
    chat_item_png: "res/graphics/chat_item.png",
    chat_item1_png: "res/graphics/chat_item1.png",
    chat_item2_png: "res/graphics/chat_item2.png",
    bubble_1_png: "res/graphics/bubble_1.png",
    chat_delete_png: "res/graphics/chat_delete.png",
    chat_exit_png: "res/graphics/chat_exit.png",
    chat_robot_png: "res/graphics/chat_robot.png",
    chat_setup_png: "res/graphics/chat_setup.png",
    send_normal_png: "res/graphics/send_normal.png",
    bg_chat_png: "res/background/bg_face.png",
    center_jpg: "res/graphics/center.jpg",
    point_png: "res/graphics/point.png",
    scale9_png: "res/graphics/scale9.png",
    biaoqing2: "res/biaoqing2.jpg",

    about_hsharmaLogo_png: "res/about_hsharmaLogo.png",
    gamebg_jpg:"res/gamebg.jpg",
    mjtt_plist:"res/mjtt.plist",
    // ,
    // playermodule_proto:"res/proto/PlayerModule.proto"
    mjtt_png:"res/mjtt.png",
    slider_bar_png:"res/slider_bar.png",
    slider_ball_normal_png:"res/slider_ball_normal.png",
    slider_process_png:"res/slider_process.png",
    button_sound_on_png:"res/button_sound_on.png",
    button_sound_off_png:"res/button_sound_off.png",
    button_close_png:"res/button_close.png",

    //icon
    background_userInfo:"res/graphics/background_userInfo.jpg",
    background_userInfo2:"res/graphics/background_userInfo2.jpeg",
    logo_bg:"res/graphics/logo_bg.png",
    ready:"res/graphics/ready.png",
    ready1:"res/graphics/ready1.png",
    kuang:"res/graphics/kuang.png",
    gold_png:"res/graphics/gold.png",
    roomCard_png:"res/graphics/roomCard.png",
    add_png:"res/graphics/add.png",
    exitLogin_png:"res/graphics/exitLogin.png",
    menu_bg2_jpg:"res/graphics/menu_bg2.jpg",
    back_png:"res/graphics/back.png",
    num_bg_png:"res/graphics/num_bg.png",


    prepare_png:"res/plist/prepare.png",
    prepare_plist:"res/plist/prepare.plist",
    scene_png:"res/plist/scene.png",
    scene_plist:"res/plist/scene.plist",

    expression_png:"res/plist/expression.png",
    expression_plist:"res/plist/expression.plist",

    bao_png:"res/plist/bao.png",
    bao_plist:"res/plist/bao.plist",
    blow_png:"res/plist/blow.png",
    blow_plist:"res/plist/blow.plist",
    fly_plist:"res/plist/fly.plist",
    fly_png:"res/plist/fly.png",
    lou_png:"res/plist/lou.png",
    lou_plist:"res/plist/lou.plist",
    pic_input:"res/pic_input_1.png",

    bg1_png:"res/background/bg1.png",
    bg_create_png:"res/background/bg_create.png",
    bg_dialog_png:"res/background/bg_dialog.png",
    bg_face_png:"res/background/bg_face.png",
    bg_finish_png:"res/background/bg_finish.png",
    bg_full_1_png:"res/background/bg_full_1.png",
    bg_full_2_png:"res/background/bg_full_2.png",
    bg_full_3_png:"res/background/bg_full_3.png",
    bg_help_png:"res/background/bg_help.png",
    bg_info_png:"res/background/bg_info.png",
    bg_middle_png:"res/background/bg_middle.png",
    bg_search_png:"res/background/bg_search.png",
    bg_setup_png:"res/background/bg_setup.png",
    bg_password_png:"res/background/bg_password.png",
    k_red_png:"res/k_red.png",
    node_png:"res/node.png",



    chi_mp3:"res/sounds/chi1.mp3",
    playCard_mp3:"res/sounds/chupai.mp3",
    peng_mp3:"res/sounds/peng1.mp3",
    gang_mp3:"res/sounds/gang1.mp3",
    hu_mp3:"res/sounds/hu1.mp3",
    mjt1_mp3:"res/sounds/mjt1.mp3",
    mjt2_mp3:"res/sounds/mjt2.mp3",
    mjt3_mp3:"res/sounds/mjt3.mp3",
    mjt4_mp3:"res/sounds/mjt4.mp3",
    mjt5_mp3:"res/sounds/mjt5.mp3",
    mjt6_mp3:"res/sounds/mjt6.mp3",
    mjt7_mp3:"res/sounds/mjt7.mp3",
    mjt8_mp3:"res/sounds/mjt8.mp3",
    mjt9_mp3:"res/sounds/mjt9.mp3",
    mjt10_mp3:"res/sounds/mjt10.mp3",
    mjt11_mp3:"res/sounds/mjt11.mp3",
    mjt12_mp3:"res/sounds/mjt12.mp3",
    mjt13_mp3:"res/sounds/mjt13.mp3",
    mjt14_mp3:"res/sounds/mjt14.mp3",
    mjt15_mp3:"res/sounds/mjt15.mp3",
    mjt16_mp3:"res/sounds/mjt16.mp3",
    mjt17_mp3:"res/sounds/mjt17.mp3",
    mjt18_mp3:"res/sounds/mjt18.mp3",
    mjt19_mp3:"res/sounds/mjt19.mp3",
    mjt20_mp3:"res/sounds/mjt20.mp3",
    mjt21_mp3:"res/sounds/mjt21.mp3",
    mjt22_mp3:"res/sounds/mjt22.mp3",
    mjt23_mp3:"res/sounds/mjt23.mp3",
    mjt24_mp3:"res/sounds/mjt24.mp3",
    mjt25_mp3:"res/sounds/mjt25.mp3",
    mjt26_mp3:"res/sounds/mjt26.mp3",
    mjt27_mp3:"res/sounds/mjt27.mp3",
    mjt33_mp3:"res/sounds/mjt33.mp3",

};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
